%YAML:1.0
curr_field: red
red_field:
  feather:
    r: 0.8
    g: 1.1
    b: -1.3
  head:
    r: -1.5
    g: -1.2
    b: 1.0
  shaft:
    r: 1.05
    g: 0.45
    b: -0.55
blue_field:
  feather:
    r: 1
    g: 0.6
    b: 0
  head:
    r: 1.0
    g: 0.2
    b: 0.2
  shaft:
    # r: 0.6
    # g: 0.22
    # b: 0.1
    r: 0.65
    g: 0.32
    b: 0.05